#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/tags.$$"' EXIT INT TERM
git ls-files | \
  "${CTAGS:-ctags}" --tag-relative=yes -L - -f"$dir/tags.$$" --languages=-sql --exclude='*.json' --exclude='*.min.js' --exclude='*.min.css'
mv "$dir/tags.$$" "$dir/tags"
