export GOPATH="$HOME/code/go"
export HISTIGNORE="clear:bg:fg:cd:cd -:exit:date:w:* --help"
export PATH="/usr/local/bin:/usr/local/sbin:$HOME/Library/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$GOPATH/bin:$PATH"
eval "$(rbenv init -)"
